// Using inline type imports to avoid circular dependency with onboarding.ts
import type {
  SpiritualBackground,
  LearningStyle,
  CommunityPreference,
  CurrentSeason,
} from '@/types/onboarding';

// ============ Code Mappings ============

const BG_CODE: Record<SpiritualBackground, string> = {
  new_to_faith: 'NEW',
  believer_going_deeper: 'DEEPER',
  pastor_leader: 'LEADER',
  seminary_student: 'STUDENT',
  exploring_faith: 'EXPLORING',
};

const LEARNING_CODE: Record<LearningStyle, string> = {
  reading_reflection: 'READ',
  visual_learner: 'VISUAL',
  conversation_discussion: 'DISCUSS',
  hands_on_interactive: 'INTERACTIVE',
  connections_patterns: 'PATTERNS',
};

const COMMUNITY_CODE: Record<CommunityPreference, string> = {
  individual_study: 'SOLO',
  small_group: 'GROUP',
  group_leader: 'FACILITATE',
  seeking_community: 'SEEKING',
  both_personal_group: 'MIXED',
};

const SEASON_CODE: Record<CurrentSeason, string> = {
  deeper_relationship: 'RELATIONSHIP',
  questions_doubts: 'DOUBTS',
  difficult_situation: 'CRISIS',
  ministry_preparation: 'MINISTRY',
  understand_bible: 'UNDERSTANDING',
  spiritual_growth: 'GROWTH',
};

// ============ 750 Persona Names ============

const PERSONA_NAMES: Record<string, string> = {
  // --- NEW + READ (30) ---
  'NEW-READ-SOLO-RELATIONSHIP': 'The Quiet Seeker',
  'NEW-READ-SOLO-DOUBTS': 'The Thoughtful Questioner',
  'NEW-READ-SOLO-CRISIS': 'The Searching Soul',
  'NEW-READ-SOLO-MINISTRY': 'The Gentle Caller',
  'NEW-READ-SOLO-UNDERSTANDING': 'The Gentle Reader',
  'NEW-READ-SOLO-GROWTH': 'The Personal Pioneer',
  'NEW-READ-GROUP-RELATIONSHIP': 'The Supported Seeker',
  'NEW-READ-GROUP-DOUBTS': 'The Honest Explorer',
  'NEW-READ-GROUP-CRISIS': 'The Comforted Searcher',
  'NEW-READ-GROUP-MINISTRY': 'The Emerging Servant',
  'NEW-READ-GROUP-UNDERSTANDING': 'The Group Learner',
  'NEW-READ-GROUP-GROWTH': 'The Community Beginner',
  'NEW-READ-FACILITATE-RELATIONSHIP': 'The Reluctant Leader',
  'NEW-READ-FACILITATE-DOUBTS': 'The Questioning Guide',
  'NEW-READ-FACILITATE-CRISIS': 'The Wounded Healer',
  'NEW-READ-FACILITATE-MINISTRY': 'The Fresh Facilitator',
  'NEW-READ-FACILITATE-UNDERSTANDING': 'The Learning Leader',
  'NEW-READ-FACILITATE-GROWTH': 'The Growing Guide',
  'NEW-READ-SEEKING-RELATIONSHIP': 'The Lonely Seeker',
  'NEW-READ-SEEKING-DOUBTS': 'The Searching Mind',
  'NEW-READ-SEEKING-CRISIS': 'The Desperate Searcher',
  'NEW-READ-SEEKING-MINISTRY': 'The Solitary Servant',
  'NEW-READ-SEEKING-UNDERSTANDING': 'The Hungry Learner',
  'NEW-READ-SEEKING-GROWTH': 'The Yearning Heart',
  'NEW-READ-MIXED-RELATIONSHIP': 'The Balanced Beginner',
  'NEW-READ-MIXED-DOUBTS': 'The Flexible Scholar',
  'NEW-READ-MIXED-CRISIS': 'The Adaptive Seeker',
  'NEW-READ-MIXED-MINISTRY': 'The Versatile Servant',
  'NEW-READ-MIXED-UNDERSTANDING': 'The Open Reader',
  'NEW-READ-MIXED-GROWTH': 'The Holistic Seeker',

  // --- NEW + VISUAL (30) ---
  'NEW-VISUAL-SOLO-RELATIONSHIP': 'The Artistic Seeker',
  'NEW-VISUAL-SOLO-DOUBTS': 'The Visual Leader',
  'NEW-VISUAL-SOLO-CRISIS': 'The Creative Healer',
  'NEW-VISUAL-SOLO-MINISTRY': 'The Inspiring Facilitator',
  'NEW-VISUAL-SOLO-UNDERSTANDING': 'The Teaching Artist',
  'NEW-VISUAL-SOLO-GROWTH': 'The Visual Shepherd',
  'NEW-VISUAL-GROUP-RELATIONSHIP': 'The Artistic Wanderer',
  'NEW-VISUAL-GROUP-DOUBTS': 'The Creative Refuge',
  'NEW-VISUAL-GROUP-CRISIS': 'The Inspired Nomad',
  'NEW-VISUAL-GROUP-MINISTRY': 'The Picture Seeker',
  'NEW-VISUAL-GROUP-UNDERSTANDING': 'The Colorful Journey',
  'NEW-VISUAL-GROUP-GROWTH': 'The Creative Community',
  'NEW-VISUAL-FACILITATE-RELATIONSHIP': 'The Artistic Guide',
  'NEW-VISUAL-FACILITATE-DOUBTS': 'The Creative Healer',
  'NEW-VISUAL-FACILITATE-CRISIS': 'The Inspiring Facilitator',
  'NEW-VISUAL-FACILITATE-MINISTRY': 'The Teaching Artist',
  'NEW-VISUAL-FACILITATE-UNDERSTANDING': 'The Teaching Artist',
  'NEW-VISUAL-FACILITATE-GROWTH': 'The Visual Shepherd',
  'NEW-VISUAL-SEEKING-RELATIONSHIP': 'The Artistic Wanderer',
  'NEW-VISUAL-SEEKING-DOUBTS': 'The Visual Seeker',
  'NEW-VISUAL-SEEKING-CRISIS': 'The Creative Refuge',
  'NEW-VISUAL-SEEKING-MINISTRY': 'The Inspired Nomad',
  'NEW-VISUAL-SEEKING-UNDERSTANDING': 'The Picture Seeker',
  'NEW-VISUAL-SEEKING-GROWTH': 'The Colorful Journey',
  'NEW-VISUAL-MIXED-RELATIONSHIP': 'The Flexible Artist',
  'NEW-VISUAL-MIXED-DOUBTS': 'The Adaptive Visualizer',
  'NEW-VISUAL-MIXED-CRISIS': 'The Creative Adapter',
  'NEW-VISUAL-MIXED-MINISTRY': 'The Versatile Creator',
  'NEW-VISUAL-MIXED-UNDERSTANDING': 'The Visual Explorer',
  'NEW-VISUAL-MIXED-GROWTH': 'The Creative Synthesizer',

  // --- NEW + DISCUSS (30) ---
  'NEW-DISCUSS-SOLO-RELATIONSHIP': 'The Conversational Hermit',
  'NEW-DISCUSS-SOLO-DOUBTS': 'The Internal Dialoguer',
  'NEW-DISCUSS-SOLO-CRISIS': 'The Talking Processor',
  'NEW-DISCUSS-SOLO-MINISTRY': 'The Vocal Contemplative',
  'NEW-DISCUSS-SOLO-UNDERSTANDING': 'The Speaking Student',
  'NEW-DISCUSS-SOLO-GROWTH': 'The Verbal Seeker',
  'NEW-DISCUSS-GROUP-RELATIONSHIP': 'The Talkative Seeker',
  'NEW-DISCUSS-GROUP-DOUBTS': 'The Group Questioner',
  'NEW-DISCUSS-GROUP-CRISIS': 'The Sharing Survivor',
  'NEW-DISCUSS-GROUP-MINISTRY': 'The Conversational Servant',
  'NEW-DISCUSS-GROUP-UNDERSTANDING': 'The Discussion Learner',
  'NEW-DISCUSS-GROUP-GROWTH': 'The Social Beginner',
  'NEW-DISCUSS-FACILITATE-RELATIONSHIP': 'The Natural Leader',
  'NEW-DISCUSS-FACILITATE-DOUBTS': 'The Question Master',
  'NEW-DISCUSS-FACILITATE-CRISIS': 'The Healing Facilitator',
  'NEW-DISCUSS-FACILITATE-MINISTRY': 'The Born Guide',
  'NEW-DISCUSS-FACILITATE-UNDERSTANDING': 'The Teaching Talker',
  'NEW-DISCUSS-FACILITATE-GROWTH': 'The Growing Leader',
  'NEW-DISCUSS-SEEKING-RELATIONSHIP': 'The Social Seeker',
  'NEW-DISCUSS-SEEKING-DOUBTS': 'The Community Questioner',
  'NEW-DISCUSS-SEEKING-CRISIS': 'The Connection Seeker',
  'NEW-DISCUSS-SEEKING-MINISTRY': 'The People Person',
  'NEW-DISCUSS-SEEKING-UNDERSTANDING': 'The Social Student',
  'NEW-DISCUSS-SEEKING-GROWTH': 'The Relational Learner',
  'NEW-DISCUSS-MIXED-RELATIONSHIP': 'The Balanced Talker',
  'NEW-DISCUSS-MIXED-DOUBTS': 'The Flexible Questioner',
  'NEW-DISCUSS-MIXED-CRISIS': 'The Adaptive Processor',
  'NEW-DISCUSS-MIXED-MINISTRY': 'The Versatile Speaker',
  'NEW-DISCUSS-MIXED-UNDERSTANDING': 'The Social Synthesizer',
  'NEW-DISCUSS-MIXED-GROWTH': 'The Holistic Communicator',

  // --- NEW + INTERACTIVE (30) ---
  'NEW-INTERACTIVE-SOLO-RELATIONSHIP': 'The Hands-On Seeker',
  'NEW-INTERACTIVE-SOLO-DOUBTS': 'The Active Questioner',
  'NEW-INTERACTIVE-SOLO-CRISIS': 'The Doing Processor',
  'NEW-INTERACTIVE-SOLO-MINISTRY': 'The Practical Servant',
  'NEW-INTERACTIVE-SOLO-UNDERSTANDING': 'The Kinesthetic Learner',
  'NEW-INTERACTIVE-SOLO-GROWTH': 'The Action-Oriented Seeker',
  'NEW-INTERACTIVE-GROUP-RELATIONSHIP': 'The Group Experiencer',
  'NEW-INTERACTIVE-GROUP-DOUBTS': 'The Active Inquirer',
  'NEW-INTERACTIVE-GROUP-CRISIS': 'The Hands-On Healer',
  'NEW-INTERACTIVE-GROUP-MINISTRY': 'The Practical Team Player',
  'NEW-INTERACTIVE-GROUP-UNDERSTANDING': 'The Interactive Learner',
  'NEW-INTERACTIVE-GROUP-GROWTH': 'The Active Community',
  'NEW-INTERACTIVE-FACILITATE-RELATIONSHIP': 'The Experiential Leader',
  'NEW-INTERACTIVE-FACILITATE-DOUBTS': 'The Active Guide',
  'NEW-INTERACTIVE-FACILITATE-CRISIS': 'The Practical Healer',
  'NEW-INTERACTIVE-FACILITATE-MINISTRY': 'The Hands-On Facilitator',
  'NEW-INTERACTIVE-FACILITATE-UNDERSTANDING': 'The Experiential Teacher',
  'NEW-INTERACTIVE-FACILITATE-GROWTH': 'The Action Leader',
  'NEW-INTERACTIVE-SEEKING-RELATIONSHIP': 'The Active Seeker',
  'NEW-INTERACTIVE-SEEKING-DOUBTS': 'The Hands-On Questioner',
  'NEW-INTERACTIVE-SEEKING-CRISIS': 'The Practical Searcher',
  'NEW-INTERACTIVE-SEEKING-MINISTRY': 'The Action-Oriented Servant',
  'NEW-INTERACTIVE-SEEKING-UNDERSTANDING': 'The Experiential Student',
  'NEW-INTERACTIVE-SEEKING-GROWTH': 'The Interactive Journey',
  'NEW-INTERACTIVE-MIXED-RELATIONSHIP': 'The Versatile Door',
  'NEW-INTERACTIVE-MIXED-DOUBTS': 'The Adaptive Experiencer',
  'NEW-INTERACTIVE-MIXED-CRISIS': 'The Flexible Processor',
  'NEW-INTERACTIVE-MIXED-MINISTRY': 'The Multi-Modal Servant',
  'NEW-INTERACTIVE-MIXED-UNDERSTANDING': 'The Dynamic Learner',
  'NEW-INTERACTIVE-MIXED-GROWTH': 'The Holistic Actor',

  // --- NEW + PATTERNS (30) ---
  'NEW-PATTERNS-SOLO-RELATIONSHIP': 'The Pattern Seeker',
  'NEW-PATTERNS-SOLO-DOUBTS': 'The Connection Questioner',
  'NEW-PATTERNS-SOLO-CRISIS': 'The Meaning Searcher',
  'NEW-PATTERNS-SOLO-MINISTRY': 'The Systematic Servant',
  'NEW-PATTERNS-SOLO-UNDERSTANDING': 'The Detective Student',
  'NEW-PATTERNS-SOLO-GROWTH': 'The Discovery Pioneer',
  'NEW-PATTERNS-GROUP-RELATIONSHIP': 'The Group Detective',
  'NEW-PATTERNS-GROUP-DOUBTS': 'The Collective Questioner',
  'NEW-PATTERNS-GROUP-CRISIS': 'The Shared Searcher',
  'NEW-PATTERNS-GROUP-MINISTRY': 'The Team Detective',
  'NEW-PATTERNS-GROUP-UNDERSTANDING': 'The Pattern Learner',
  'NEW-PATTERNS-GROUP-GROWTH': 'The Discovery Community',
  'NEW-PATTERNS-FACILITATE-RELATIONSHIP': 'The Pattern Leader',
  'NEW-PATTERNS-FACILITATE-DOUBTS': 'The Detective Guide',
  'NEW-PATTERNS-FACILITATE-CRISIS': 'The Connection Healer',
  'NEW-PATTERNS-FACILITATE-MINISTRY': 'The Systematic Facilitator',
  'NEW-PATTERNS-FACILITATE-UNDERSTANDING': 'The Discovery Teacher',
  'NEW-PATTERNS-FACILITATE-GROWTH': 'The Pattern Shepherd',
  'NEW-PATTERNS-SEEKING-RELATIONSHIP': 'The Connection Seeker',
  'NEW-PATTERNS-SEEKING-DOUBTS': 'The Pattern Questioner',
  'NEW-PATTERNS-SEEKING-CRISIS': 'The Meaning Hunter',
  'NEW-PATTERNS-SEEKING-MINISTRY': 'The Detective Servant',
  'NEW-PATTERNS-SEEKING-UNDERSTANDING': 'The Discovery Seeker',
  'NEW-PATTERNS-SEEKING-GROWTH': 'The Pattern Journey',
  'NEW-PATTERNS-MIXED-RELATIONSHIP': 'The Flexible Detective',
  'NEW-PATTERNS-MIXED-DOUBTS': 'The Adaptive Pattern Finder',
  'NEW-PATTERNS-MIXED-CRISIS': 'The Versatile Searcher',
  'NEW-PATTERNS-MIXED-MINISTRY': 'The Multi-Modal Detective',
  'NEW-PATTERNS-MIXED-UNDERSTANDING': 'The Holistic Discoverer',
  'NEW-PATTERNS-MIXED-GROWTH': 'The Comprehensive Explorer',

  // --- DEEPER + READ (30) ---
  'DEEPER-READ-SOLO-RELATIONSHIP': 'The Solitary Mystic',
  'DEEPER-READ-SOLO-DOUBTS': 'The Wrestling Scholar',
  'DEEPER-READ-SOLO-CRISIS': 'The Contemplative Warrior',
  'DEEPER-READ-SOLO-MINISTRY': 'The Prepared Servant',
  'DEEPER-READ-SOLO-UNDERSTANDING': 'The Mature Student',
  'DEEPER-READ-SOLO-GROWTH': 'The Deep Diver',
  'DEEPER-READ-GROUP-RELATIONSHIP': 'The Seasoned Seeker',
  'DEEPER-READ-GROUP-DOUBTS': 'The Mature Questioner',
  'DEEPER-READ-GROUP-CRISIS': 'The Weathered Survivor',
  'DEEPER-READ-GROUP-MINISTRY': 'The Experienced Servant',
  'DEEPER-READ-GROUP-UNDERSTANDING': 'The Veteran Learner',
  'DEEPER-READ-GROUP-GROWTH': 'The Growing Veteran',
  'DEEPER-READ-FACILITATE-RELATIONSHIP': 'The Wise Leader',
  'DEEPER-READ-FACILITATE-DOUBTS': 'The Seasoned Guide',
  'DEEPER-READ-FACILITATE-CRISIS': 'The Experienced Healer',
  'DEEPER-READ-FACILITATE-MINISTRY': 'The Veteran Facilitator',
  'DEEPER-READ-FACILITATE-UNDERSTANDING': 'The Mature Teacher',
  'DEEPER-READ-FACILITATE-GROWTH': 'The Deep Leader',
  'DEEPER-READ-SEEKING-RELATIONSHIP': 'The Restless Veteran',
  'DEEPER-READ-SEEKING-DOUBTS': 'The Seeking Scholar',
  'DEEPER-READ-SEEKING-CRISIS': 'The Homeless Wanderer',
  'DEEPER-READ-SEEKING-MINISTRY': 'The Searching Servant',
  'DEEPER-READ-SEEKING-UNDERSTANDING': 'The Hungry Veteran',
  'DEEPER-READ-SEEKING-GROWTH': 'The Yearning Scholar',
  'DEEPER-READ-MIXED-RELATIONSHIP': 'The Balanced Veteran',
  'DEEPER-READ-MIXED-DOUBTS': 'The Flexible Scholar',
  'DEEPER-READ-MIXED-CRISIS': 'The Adaptive Veteran',
  'DEEPER-READ-MIXED-MINISTRY': 'The Versatile Reader',
  'DEEPER-READ-MIXED-UNDERSTANDING': 'The Open Scholar',
  'DEEPER-READ-MIXED-GROWTH': 'The Holistic Veteran',

  // --- DEEPER + VISUAL (30) ---
  'DEEPER-VISUAL-SOLO-RELATIONSHIP': 'The Contemplative Artist',
  'DEEPER-VISUAL-SOLO-DOUBTS': 'The Reflective Visualizer',
  'DEEPER-VISUAL-SOLO-CRISIS': 'The Artistic Warrior',
  'DEEPER-VISUAL-SOLO-MINISTRY': 'The Creative Veteran',
  'DEEPER-VISUAL-SOLO-UNDERSTANDING': 'The Visual Scholar',
  'DEEPER-VISUAL-SOLO-GROWTH': 'The Artistic Mystic',
  'DEEPER-VISUAL-GROUP-RELATIONSHIP': 'The Shared Visionary',
  'DEEPER-VISUAL-GROUP-DOUBTS': 'The Group Artist',
  'DEEPER-VISUAL-GROUP-CRISIS': 'The Community Creator',
  'DEEPER-VISUAL-GROUP-MINISTRY': 'The Visual Servant',
  'DEEPER-VISUAL-GROUP-UNDERSTANDING': 'The Collaborative Visualizer',
  'DEEPER-VISUAL-GROUP-GROWTH': 'The Creative Veteran',
  'DEEPER-VISUAL-FACILITATE-RELATIONSHIP': 'The Visionary Leader',
  'DEEPER-VISUAL-FACILITATE-DOUBTS': 'The Artistic Guide',
  'DEEPER-VISUAL-FACILITATE-CRISIS': 'The Creative Healer',
  'DEEPER-VISUAL-FACILITATE-MINISTRY': 'The Visual Facilitator',
  'DEEPER-VISUAL-FACILITATE-UNDERSTANDING': 'The Teaching Artist',
  'DEEPER-VISUAL-FACILITATE-GROWTH': 'The Creative Leader',
  'DEEPER-VISUAL-SEEKING-RELATIONSHIP': 'The Artistic Pilgrim',
  'DEEPER-VISUAL-SEEKING-DOUBTS': 'The Visual Wanderer',
  'DEEPER-VISUAL-SEEKING-CRISIS': 'The Creative Refuge',
  'DEEPER-VISUAL-SEEKING-MINISTRY': 'The Inspired Nomad',
  'DEEPER-VISUAL-SEEKING-UNDERSTANDING': 'The Seeking Artist',
  'DEEPER-VISUAL-SEEKING-GROWTH': 'The Colorful Journey',
  'DEEPER-VISUAL-MIXED-RELATIONSHIP': 'The Flexible Visionary',
  'DEEPER-VISUAL-MIXED-DOUBTS': 'The Adaptive Artist',
  'DEEPER-VISUAL-MIXED-CRISIS': 'The Versatile Creator',
  'DEEPER-VISUAL-MIXED-MINISTRY': 'The Multi-Modal Visionary',
  'DEEPER-VISUAL-MIXED-UNDERSTANDING': 'The Holistic Artist',
  'DEEPER-VISUAL-MIXED-GROWTH': 'The Creative Synthesizer',

  // --- DEEPER + DISCUSS (30) ---
  'DEEPER-DISCUSS-SOLO-RELATIONSHIP': 'The Reflective Talker',
  'DEEPER-DISCUSS-SOLO-DOUBTS': 'The Internal Debater',
  'DEEPER-DISCUSS-SOLO-CRISIS': 'The Processing Veteran',
  'DEEPER-DISCUSS-SOLO-MINISTRY': 'The Thoughtful Servant',
  'DEEPER-DISCUSS-SOLO-UNDERSTANDING': 'The Vocal Scholar',
  'DEEPER-DISCUSS-SOLO-GROWTH': 'The Speaking Mystic',
  'DEEPER-DISCUSS-GROUP-RELATIONSHIP': 'The Veteran Conversationalist',
  'DEEPER-DISCUSS-GROUP-DOUBTS': 'The Seasoned Questioner',
  'DEEPER-DISCUSS-GROUP-CRISIS': 'The Sharing Survivor',
  'DEEPER-DISCUSS-GROUP-MINISTRY': 'The Discussion Servant',
  'DEEPER-DISCUSS-GROUP-UNDERSTANDING': 'The Group Scholar',
  'DEEPER-DISCUSS-GROUP-GROWTH': 'The Mature Discussant',
  'DEEPER-DISCUSS-FACILITATE-RELATIONSHIP': 'The Wise Facilitator',
  'DEEPER-DISCUSS-FACILITATE-DOUBTS': 'The Master Questioner',
  'DEEPER-DISCUSS-FACILITATE-CRISIS': 'The Healing Guide',
  'DEEPER-DISCUSS-FACILITATE-MINISTRY': 'The Seasoned Leader',
  'DEEPER-DISCUSS-FACILITATE-UNDERSTANDING': 'The Teaching Facilitator',
  'DEEPER-DISCUSS-FACILITATE-GROWTH': 'The Growth Leader',
  'DEEPER-DISCUSS-SEEKING-RELATIONSHIP': 'The Social Pilgrim',
  'DEEPER-DISCUSS-SEEKING-DOUBTS': 'The Community Seeker',
  'DEEPER-DISCUSS-SEEKING-CRISIS': 'The Connection Hunter',
  'DEEPER-DISCUSS-SEEKING-MINISTRY': 'The Relational Servant',
  'DEEPER-DISCUSS-SEEKING-UNDERSTANDING': 'The Social Scholar',
  'DEEPER-DISCUSS-SEEKING-GROWTH': 'The Conversational Journey',
  'DEEPER-DISCUSS-MIXED-RELATIONSHIP': 'The Balanced Communicator',
  'DEEPER-DISCUSS-MIXED-DOUBTS': 'The Flexible Conversationalist',
  'DEEPER-DISCUSS-MIXED-CRISIS': 'The Adaptive Processor',
  'DEEPER-DISCUSS-MIXED-MINISTRY': 'The Versatile Speaker',
  'DEEPER-DISCUSS-MIXED-UNDERSTANDING': 'The Holistic Discussant',
  'DEEPER-DISCUSS-MIXED-GROWTH': 'The Comprehensive Talker',

  // --- DEEPER + INTERACTIVE (30) ---
  'DEEPER-INTERACTIVE-SOLO-RELATIONSHIP': 'The Contemplative Doer',
  'DEEPER-INTERACTIVE-SOLO-DOUBTS': 'The Active Scholar',
  'DEEPER-INTERACTIVE-SOLO-CRISIS': 'The Practical Warrior',
  'DEEPER-INTERACTIVE-SOLO-MINISTRY': 'The Hands-On Veteran',
  'DEEPER-INTERACTIVE-SOLO-UNDERSTANDING': 'The Kinesthetic Scholar',
  'DEEPER-INTERACTIVE-SOLO-GROWTH': 'The Active Mystic',
  'DEEPER-INTERACTIVE-GROUP-RELATIONSHIP': 'The Experiential Veteran',
  'DEEPER-INTERACTIVE-GROUP-DOUBTS': 'The Active Inquirer',
  'DEEPER-INTERACTIVE-GROUP-CRISIS': 'The Hands-On Healer',
  'DEEPER-INTERACTIVE-GROUP-MINISTRY': 'The Practical Team Player',
  'DEEPER-INTERACTIVE-GROUP-UNDERSTANDING': 'The Interactive Scholar',
  'DEEPER-INTERACTIVE-GROUP-GROWTH': 'The Active Community',
  'DEEPER-INTERACTIVE-FACILITATE-RELATIONSHIP': 'The Experiential Leader',
  'DEEPER-INTERACTIVE-FACILITATE-DOUBTS': 'The Active Guide',
  'DEEPER-INTERACTIVE-FACILITATE-CRISIS': 'The Practical Healer',
  'DEEPER-INTERACTIVE-FACILITATE-MINISTRY': 'The Hands-On Facilitator',
  'DEEPER-INTERACTIVE-FACILITATE-UNDERSTANDING': 'The Experiential Teacher',
  'DEEPER-INTERACTIVE-FACILITATE-GROWTH': 'The Action Leader',
  'DEEPER-INTERACTIVE-SEEKING-RELATIONSHIP': 'The Active Pilgrim',
  'DEEPER-INTERACTIVE-SEEKING-DOUBTS': 'The Hands-On Seeker',
  'DEEPER-INTERACTIVE-SEEKING-CRISIS': 'The Practical Searcher',
  'DEEPER-INTERACTIVE-SEEKING-MINISTRY': 'The Action Servant',
  'DEEPER-INTERACTIVE-SEEKING-UNDERSTANDING': 'The Experiential Seeker',
  'DEEPER-INTERACTIVE-SEEKING-GROWTH': 'The Interactive Journey',
  'DEEPER-INTERACTIVE-MIXED-RELATIONSHIP': 'The Versatile Doer',
  'DEEPER-INTERACTIVE-MIXED-DOUBTS': 'The Adaptive Experiencer',
  'DEEPER-INTERACTIVE-MIXED-CRISIS': 'The Flexible Warrior',
  'DEEPER-INTERACTIVE-MIXED-MINISTRY': 'The Multi-Modal Veteran',
  'DEEPER-INTERACTIVE-MIXED-UNDERSTANDING': 'The Dynamic Scholar',
  'DEEPER-INTERACTIVE-MIXED-GROWTH': 'The Holistic Actor',

  // --- DEEPER + PATTERNS (30) ---
  'DEEPER-PATTERNS-SOLO-RELATIONSHIP': 'The Contemplative Detective',
  'DEEPER-PATTERNS-SOLO-DOUBTS': 'The Pattern Wrestler',
  'DEEPER-PATTERNS-SOLO-CRISIS': 'The Meaning Warrior',
  'DEEPER-PATTERNS-SOLO-MINISTRY': 'The Systematic Veteran',
  'DEEPER-PATTERNS-SOLO-UNDERSTANDING': 'The Scholar Detective',
  'DEEPER-PATTERNS-SOLO-GROWTH': 'The Deep Explorer',
  'DEEPER-PATTERNS-GROUP-RELATIONSHIP': 'The Veteran Detective',
  'DEEPER-PATTERNS-GROUP-DOUBTS': 'The Collective Investigator',
  'DEEPER-PATTERNS-GROUP-CRISIS': 'The Shared Explorer',
  'DEEPER-PATTERNS-GROUP-MINISTRY': 'The Team Investigator',
  'DEEPER-PATTERNS-GROUP-UNDERSTANDING': 'The Pattern Scholar',
  'DEEPER-PATTERNS-GROUP-GROWTH': 'The Discovery Veteran',
  'DEEPER-PATTERNS-FACILITATE-RELATIONSHIP': 'The Pattern Leader',
  'DEEPER-PATTERNS-FACILITATE-DOUBTS': 'The Detective Guide',
  'DEEPER-PATTERNS-FACILITATE-CRISIS': 'The Connection Healer',
  'DEEPER-PATTERNS-FACILITATE-MINISTRY': 'The Systematic Leader',
  'DEEPER-PATTERNS-FACILITATE-UNDERSTANDING': 'The Discovery Teacher',
  'DEEPER-PATTERNS-FACILITATE-GROWTH': 'The Pattern Shepherd',
  'DEEPER-PATTERNS-SEEKING-RELATIONSHIP': 'The Connection Pilgrim',
  'DEEPER-PATTERNS-SEEKING-DOUBTS': 'The Pattern Seeker',
  'DEEPER-PATTERNS-SEEKING-CRISIS': 'The Meaning Hunter',
  'DEEPER-PATTERNS-SEEKING-MINISTRY': 'The Detective Servant',
  'DEEPER-PATTERNS-SEEKING-UNDERSTANDING': 'The Discovery Pilgrim',
  'DEEPER-PATTERNS-SEEKING-GROWTH': 'The Pattern Journey',
  'DEEPER-PATTERNS-MIXED-RELATIONSHIP': 'The Flexible Detective',
  'DEEPER-PATTERNS-MIXED-DOUBTS': 'The Adaptive Detective',
  'DEEPER-PATTERNS-MIXED-CRISIS': 'The Versatile Explorer',
  'DEEPER-PATTERNS-MIXED-MINISTRY': 'The Multi-Modal Detective',
  'DEEPER-PATTERNS-MIXED-UNDERSTANDING': 'The Holistic Investigator',
  'DEEPER-PATTERNS-MIXED-GROWTH': 'The Comprehensive Explorer',

  // --- LEADER + READ (30) ---
  'LEADER-READ-SOLO-RELATIONSHIP': 'The Shepherding Scholar',
  'LEADER-READ-SOLO-DOUBTS': 'The Wrestling Pastor',
  'LEADER-READ-SOLO-CRISIS': 'The Wounded Leader',
  'LEADER-READ-SOLO-MINISTRY': 'The Prepared Pastor',
  'LEADER-READ-SOLO-UNDERSTANDING': 'The Study Pastor',
  'LEADER-READ-SOLO-GROWTH': 'The Growing Shepherd',
  'LEADER-READ-GROUP-RELATIONSHIP': 'The Community Pastor',
  'LEADER-READ-GROUP-DOUBTS': 'The Honest Leader',
  'LEADER-READ-GROUP-CRISIS': 'The Transparent Pastor',
  'LEADER-READ-GROUP-MINISTRY': 'The Team Leader',
  'LEADER-READ-GROUP-UNDERSTANDING': 'The Learning Pastor',
  'LEADER-READ-GROUP-GROWTH': 'The Developing Leader',
  'LEADER-READ-FACILITATE-RELATIONSHIP': 'The Master Pastor',
  'LEADER-READ-FACILITATE-DOUBTS': 'The Guide Leader',
  'LEADER-READ-FACILITATE-CRISIS': 'The Healing Pastor',
  'LEADER-READ-FACILITATE-MINISTRY': 'The Expert Facilitator',
  'LEADER-READ-FACILITATE-UNDERSTANDING': 'The Teaching Leader',
  'LEADER-READ-FACILITATE-GROWTH': 'The Formation Leader',
  'LEADER-READ-SEEKING-RELATIONSHIP': 'The Lonely Pastor',
  'LEADER-READ-SEEKING-DOUBTS': 'The Seeking Leader',
  'LEADER-READ-SEEKING-CRISIS': 'The Isolated Pastor',
  'LEADER-READ-SEEKING-MINISTRY': 'The Searching Shepherd',
  'LEADER-READ-SEEKING-UNDERSTANDING': 'The Hungry Pastor',
  'LEADER-READ-SEEKING-GROWTH': 'The Yearning Leader',
  'LEADER-READ-MIXED-RELATIONSHIP': 'The Balanced Pastor',
  'LEADER-READ-MIXED-DOUBTS': 'The Flexible Leader',
  'LEADER-READ-MIXED-CRISIS': 'The Adaptive Pastor',
  'LEADER-READ-MIXED-MINISTRY': 'The Versatile Shepherd',
  'LEADER-READ-MIXED-UNDERSTANDING': 'The Holistic Pastor',
  'LEADER-READ-MIXED-GROWTH': 'The Complete Leader',

  // --- LEADER + VISUAL (30) ---
  'LEADER-VISUAL-SOLO-RELATIONSHIP': 'The Visionary Pastor',
  'LEADER-VISUAL-SOLO-DOUBTS': 'The Artistic Leader',
  'LEADER-VISUAL-SOLO-CRISIS': 'The Creative Shepherd',
  'LEADER-VISUAL-SOLO-MINISTRY': 'The Visual Pastor',
  'LEADER-VISUAL-SOLO-UNDERSTANDING': 'The Illustrative Leader',
  'LEADER-VISUAL-SOLO-GROWTH': 'The Imaginative Pastor',
  'LEADER-VISUAL-GROUP-RELATIONSHIP': 'The Community Visionary',
  'LEADER-VISUAL-GROUP-DOUBTS': 'The Group Artist',
  'LEADER-VISUAL-GROUP-CRISIS': 'The Creative Healer',
  'LEADER-VISUAL-GROUP-MINISTRY': 'The Visual Team Leader',
  'LEADER-VISUAL-GROUP-UNDERSTANDING': 'The Collaborative Pastor',
  'LEADER-VISUAL-GROUP-GROWTH': 'The Creative Community',
  'LEADER-VISUAL-FACILITATE-RELATIONSHIP': 'The Master Visionary',
  'LEADER-VISUAL-FACILITATE-DOUBTS': 'The Artistic Facilitator',
  'LEADER-VISUAL-FACILITATE-CRISIS': 'The Creative Guide',
  'LEADER-VISUAL-FACILITATE-MINISTRY': 'The Visual Expert',
  'LEADER-VISUAL-FACILITATE-UNDERSTANDING': 'The Teaching Artist',
  'LEADER-VISUAL-FACILITATE-GROWTH': 'The Creative Shepherd',
  'LEADER-VISUAL-SEEKING-RELATIONSHIP': 'The Artistic Pilgrim',
  'LEADER-VISUAL-SEEKING-DOUBTS': 'The Visual Wanderer',
  'LEADER-VISUAL-SEEKING-CRISIS': 'The Creative Searcher',
  'LEADER-VISUAL-SEEKING-MINISTRY': 'The Inspired Leader',
  'LEADER-VISUAL-SEEKING-UNDERSTANDING': 'The Seeking Artist',
  'LEADER-VISUAL-SEEKING-GROWTH': 'The Visual Journey',
  'LEADER-VISUAL-MIXED-RELATIONSHIP': 'The Flexible Visionary',
  'LEADER-VISUAL-MIXED-DOUBTS': 'The Adaptive Artist',
  'LEADER-VISUAL-MIXED-CRISIS': 'The Versatile Creator',
  'LEADER-VISUAL-MIXED-MINISTRY': 'The Multi-Modal Pastor',
  'LEADER-VISUAL-MIXED-UNDERSTANDING': 'The Holistic Visionary',
  'LEADER-VISUAL-MIXED-GROWTH': 'The Complete Artist',

  // --- LEADER + DISCUSS (30) ---
  'LEADER-DISCUSS-SOLO-RELATIONSHIP': 'The Reflective Pastor',
  'LEADER-DISCUSS-SOLO-DOUBTS': 'The Processing Leader',
  'LEADER-DISCUSS-SOLO-CRISIS': 'The Talking Shepherd',
  'LEADER-DISCUSS-SOLO-MINISTRY': 'The Speaking Leader',
  'LEADER-DISCUSS-SOLO-UNDERSTANDING': 'The Vocal Pastor',
  'LEADER-DISCUSS-SOLO-GROWTH': 'The Verbal Pastor',
  'LEADER-DISCUSS-GROUP-RELATIONSHIP': 'The Master Communicator',
  'LEADER-DISCUSS-GROUP-DOUBTS': 'The Honest Pastor',
  'LEADER-DISCUSS-GROUP-CRISIS': 'The Sharing Leader',
  'LEADER-DISCUSS-GROUP-MINISTRY': 'The Discussion Pastor',
  'LEADER-DISCUSS-GROUP-UNDERSTANDING': 'The Conversational Leader',
  'LEADER-DISCUSS-GROUP-GROWTH': 'The Talking Shepherd',
  'LEADER-DISCUSS-FACILITATE-RELATIONSHIP': 'The Ultimate Facilitator',
  'LEADER-DISCUSS-FACILITATE-DOUBTS': 'The Master Guide',
  'LEADER-DISCUSS-FACILITATE-CRISIS': 'The Healing Leader',
  'LEADER-DISCUSS-FACILITATE-MINISTRY': 'The Supreme Leader',
  'LEADER-DISCUSS-FACILITATE-UNDERSTANDING': 'The Teaching Master',
  'LEADER-DISCUSS-FACILITATE-GROWTH': 'The Formation Expert',
  'LEADER-DISCUSS-SEEKING-RELATIONSHIP': 'The Social Pastor',
  'LEADER-DISCUSS-SEEKING-DOUBTS': 'The Community Leader',
  'LEADER-DISCUSS-SEEKING-CRISIS': 'The Connection Pastor',
  'LEADER-DISCUSS-SEEKING-MINISTRY': 'The Relational Shepherd',
  'LEADER-DISCUSS-SEEKING-UNDERSTANDING': 'The Social Leader',
  'LEADER-DISCUSS-SEEKING-GROWTH': 'The Conversational Journey',
  'LEADER-DISCUSS-MIXED-RELATIONSHIP': 'The Balanced Communicator',
  'LEADER-DISCUSS-MIXED-DOUBTS': 'The Flexible Pastor',
  'LEADER-DISCUSS-MIXED-CRISIS': 'The Adaptive Leader',
  'LEADER-DISCUSS-MIXED-MINISTRY': 'The Versatile Pastor',
  'LEADER-DISCUSS-MIXED-UNDERSTANDING': 'The Holistic Communicator',
  'LEADER-DISCUSS-MIXED-GROWTH': 'The Complete Leader',

  // --- LEADER + INTERACTIVE (30) ---
  'LEADER-INTERACTIVE-SOLO-RELATIONSHIP': 'The Hands-On Pastor',
  'LEADER-INTERACTIVE-SOLO-DOUBTS': 'The Active Leader',
  'LEADER-INTERACTIVE-SOLO-CRISIS': 'The Practical Shepherd',
  'LEADER-INTERACTIVE-SOLO-MINISTRY': 'The Experiential Pastor',
  'LEADER-INTERACTIVE-SOLO-UNDERSTANDING': 'The Kinesthetic Leader',
  'LEADER-INTERACTIVE-SOLO-GROWTH': 'The Action Pastor',
  'LEADER-INTERACTIVE-GROUP-RELATIONSHIP': 'The Experiential Leader',
  'LEADER-INTERACTIVE-GROUP-DOUBTS': 'The Active Pastor',
  'LEADER-INTERACTIVE-GROUP-CRISIS': 'The Hands-On Healer',
  'LEADER-INTERACTIVE-GROUP-MINISTRY': 'The Practical Leader',
  'LEADER-INTERACTIVE-GROUP-UNDERSTANDING': 'The Interactive Pastor',
  'LEADER-INTERACTIVE-GROUP-GROWTH': 'The Active Shepherd',
  'LEADER-INTERACTIVE-FACILITATE-RELATIONSHIP': 'The Master Experiencer',
  'LEADER-INTERACTIVE-FACILITATE-DOUBTS': 'The Active Guide',
  'LEADER-INTERACTIVE-FACILITATE-CRISIS': 'The Practical Expert',
  'LEADER-INTERACTIVE-FACILITATE-MINISTRY': 'The Hands-On Master',
  'LEADER-INTERACTIVE-FACILITATE-UNDERSTANDING': 'The Experiential Expert',
  'LEADER-INTERACTIVE-FACILITATE-GROWTH': 'The Action Leader',
  'LEADER-INTERACTIVE-SEEKING-RELATIONSHIP': 'The Active Pilgrim',
  'LEADER-INTERACTIVE-SEEKING-DOUBTS': 'The Hands-On Seeker',
  'LEADER-INTERACTIVE-SEEKING-CRISIS': 'The Practical Searcher',
  'LEADER-INTERACTIVE-SEEKING-MINISTRY': 'The Action Servant',
  'LEADER-INTERACTIVE-SEEKING-UNDERSTANDING': 'The Experiential Seeker',
  'LEADER-INTERACTIVE-SEEKING-GROWTH': 'The Interactive Journey',
  'LEADER-INTERACTIVE-MIXED-RELATIONSHIP': 'The Versatile Doer',
  'LEADER-INTERACTIVE-MIXED-DOUBTS': 'The Adaptive Experiencer',
  'LEADER-INTERACTIVE-MIXED-CRISIS': 'The Flexible Leader',
  'LEADER-INTERACTIVE-MIXED-MINISTRY': 'The Multi-Modal Pastor',
  'LEADER-INTERACTIVE-MIXED-UNDERSTANDING': 'The Dynamic Leader',
  'LEADER-INTERACTIVE-MIXED-GROWTH': 'The Holistic Actor',

  // --- LEADER + PATTERNS (30) ---
  'LEADER-PATTERNS-SOLO-RELATIONSHIP': 'The Detective Pastor',
  'LEADER-PATTERNS-SOLO-DOUBTS': 'The Pattern Leader',
  'LEADER-PATTERNS-SOLO-CRISIS': 'The Meaning Shepherd',
  'LEADER-PATTERNS-SOLO-MINISTRY': 'The Systematic Pastor',
  'LEADER-PATTERNS-SOLO-UNDERSTANDING': 'The Scholar Pastor',
  'LEADER-PATTERNS-SOLO-GROWTH': 'The Discovery Leader',
  'LEADER-PATTERNS-GROUP-RELATIONSHIP': 'The Community Detective',
  'LEADER-PATTERNS-GROUP-DOUBTS': 'The Collective Pastor',
  'LEADER-PATTERNS-GROUP-CRISIS': 'The Shared Explorer',
  'LEADER-PATTERNS-GROUP-MINISTRY': 'The Team Detective',
  'LEADER-PATTERNS-GROUP-UNDERSTANDING': 'The Pattern Pastor',
  'LEADER-PATTERNS-GROUP-GROWTH': 'The Discovery Leader',
  'LEADER-PATTERNS-FACILITATE-RELATIONSHIP': 'The Master Detective',
  'LEADER-PATTERNS-FACILITATE-DOUBTS': 'The Pattern Guide',
  'LEADER-PATTERNS-FACILITATE-CRISIS': 'The Connection Expert',
  'LEADER-PATTERNS-FACILITATE-MINISTRY': 'The Systematic Master',
  'LEADER-PATTERNS-FACILITATE-UNDERSTANDING': 'The Discovery Expert',
  'LEADER-PATTERNS-FACILITATE-GROWTH': 'The Pattern Shepherd',
  'LEADER-PATTERNS-SEEKING-RELATIONSHIP': 'The Connection Pastor',
  'LEADER-PATTERNS-SEEKING-DOUBTS': 'The Pattern Seeker',
  'LEADER-PATTERNS-SEEKING-CRISIS': 'The Meaning Hunter',
  'LEADER-PATTERNS-SEEKING-MINISTRY': 'The Detective Servant',
  'LEADER-PATTERNS-SEEKING-UNDERSTANDING': 'The Discovery Pastor',
  'LEADER-PATTERNS-SEEKING-GROWTH': 'The Pattern Journey',
  'LEADER-PATTERNS-MIXED-RELATIONSHIP': 'The Flexible Detective',
  'LEADER-PATTERNS-MIXED-DOUBTS': 'The Adaptive Pastor',
  'LEADER-PATTERNS-MIXED-CRISIS': 'The Versatile Explorer',
  'LEADER-PATTERNS-MIXED-MINISTRY': 'The Multi-Modal Detective',
  'LEADER-PATTERNS-MIXED-UNDERSTANDING': 'The Holistic Pastor',
  'LEADER-PATTERNS-MIXED-GROWTH': 'The Comprehensive Leader',

  // --- STUDENT + READ (30) ---
  'STUDENT-READ-SOLO-RELATIONSHIP': 'The Scholarly Mystic',
  'STUDENT-READ-SOLO-DOUBTS': 'The Academic Wrestler',
  'STUDENT-READ-SOLO-CRISIS': 'The Studying Survivor',
  'STUDENT-READ-SOLO-MINISTRY': 'The Preparing Scholar',
  'STUDENT-READ-SOLO-UNDERSTANDING': 'The Dedicated Student',
  'STUDENT-READ-SOLO-GROWTH': 'The Growing Scholar',
  'STUDENT-READ-GROUP-RELATIONSHIP': 'The Community Scholar',
  'STUDENT-READ-GROUP-DOUBTS': 'The Group Student',
  'STUDENT-READ-GROUP-CRISIS': 'The Supported Learner',
  'STUDENT-READ-GROUP-MINISTRY': 'The Team Student',
  'STUDENT-READ-GROUP-UNDERSTANDING': 'The Collaborative Student',
  'STUDENT-READ-GROUP-GROWTH': 'The Learning Community',
  'STUDENT-READ-FACILITATE-RELATIONSHIP': 'The Teaching Student',
  'STUDENT-READ-FACILITATE-DOUBTS': 'The Student Guide',
  'STUDENT-READ-FACILITATE-CRISIS': 'The Healing Scholar',
  'STUDENT-READ-FACILITATE-MINISTRY': 'The Leading Learner',
  'STUDENT-READ-FACILITATE-UNDERSTANDING': 'The Student Teacher',
  'STUDENT-READ-FACILITATE-GROWTH': 'The Facilitating Scholar',
  'STUDENT-READ-SEEKING-RELATIONSHIP': 'The Searching Scholar',
  'STUDENT-READ-SEEKING-DOUBTS': 'The Seeking Student',
  'STUDENT-READ-SEEKING-CRISIS': 'The Lost Learner',
  'STUDENT-READ-SEEKING-MINISTRY': 'The Hungry Scholar',
  'STUDENT-READ-SEEKING-UNDERSTANDING': 'The Yearning Student',
  'STUDENT-READ-SEEKING-GROWTH': 'The Questing Scholar',
  'STUDENT-READ-MIXED-RELATIONSHIP': 'The Balanced Scholar',
  'STUDENT-READ-MIXED-DOUBTS': 'The Flexible Student',
  'STUDENT-READ-MIXED-CRISIS': 'The Adaptive Learner',
  'STUDENT-READ-MIXED-MINISTRY': 'The Versatile Scholar',
  'STUDENT-READ-MIXED-UNDERSTANDING': 'The Holistic Student',
  'STUDENT-READ-MIXED-GROWTH': 'The Complete Scholar',

  // --- STUDENT + VISUAL (30) ---
  'STUDENT-VISUAL-SOLO-RELATIONSHIP': 'The Artistic Student',
  'STUDENT-VISUAL-SOLO-DOUBTS': 'The Visual Student',
  'STUDENT-VISUAL-SOLO-CRISIS': 'The Creative Learner',
  'STUDENT-VISUAL-SOLO-MINISTRY': 'The Inspired Student',
  'STUDENT-VISUAL-SOLO-UNDERSTANDING': 'The Picture Student',
  'STUDENT-VISUAL-SOLO-GROWTH': 'The Imaginative Scholar',
  'STUDENT-VISUAL-GROUP-RELATIONSHIP': 'The Collaborative Artist',
  'STUDENT-VISUAL-GROUP-DOUBTS': 'The Group Visualizer',
  'STUDENT-VISUAL-GROUP-CRISIS': 'The Supported Creator',
  'STUDENT-VISUAL-GROUP-MINISTRY': 'The Visual Team Player',
  'STUDENT-VISUAL-GROUP-UNDERSTANDING': 'The Collaborative Learner',
  'STUDENT-VISUAL-GROUP-GROWTH': 'The Creative Community',
  'STUDENT-VISUAL-FACILITATE-RELATIONSHIP': 'The Visual Leader',
  'STUDENT-VISUAL-FACILITATE-DOUBTS': 'The Artistic Guide',
  'STUDENT-VISUAL-FACILITATE-CRISIS': 'The Creative Healer',
  'STUDENT-VISUAL-FACILITATE-MINISTRY': 'The Inspiring Facilitator',
  'STUDENT-VISUAL-FACILITATE-UNDERSTANDING': 'The Teaching Artist',
  'STUDENT-VISUAL-FACILITATE-GROWTH': 'The Visual Shepherd',
  'STUDENT-VISUAL-SEEKING-RELATIONSHIP': 'The Artistic Seeker',
  'STUDENT-VISUAL-SEEKING-DOUBTS': 'The Visual Wanderer',
  'STUDENT-VISUAL-SEEKING-CRISIS': 'The Creative Refuge',
  'STUDENT-VISUAL-SEEKING-MINISTRY': 'The Inspired Nomad',
  'STUDENT-VISUAL-SEEKING-UNDERSTANDING': 'The Picture Seeker',
  'STUDENT-VISUAL-SEEKING-GROWTH': 'The Colorful Journey',
  'STUDENT-VISUAL-MIXED-RELATIONSHIP': 'The Flexible Artist',
  'STUDENT-VISUAL-MIXED-DOUBTS': 'The Adaptive Visualizer',
  'STUDENT-VISUAL-MIXED-CRISIS': 'The Creative Adapter',
  'STUDENT-VISUAL-MIXED-MINISTRY': 'The Versatile Creator',
  'STUDENT-VISUAL-MIXED-UNDERSTANDING': 'The Visual Explorer',
  'STUDENT-VISUAL-MIXED-GROWTH': 'The Creative Synthesizer',

  // --- STUDENT + DISCUSS (30) ---
  'STUDENT-DISCUSS-SOLO-RELATIONSHIP': 'The Talking Scholar',
  'STUDENT-DISCUSS-SOLO-DOUBTS': 'The Debating Student',
  'STUDENT-DISCUSS-SOLO-CRISIS': 'The Processing Learner',
  'STUDENT-DISCUSS-SOLO-MINISTRY': 'The Vocal Scholar',
  'STUDENT-DISCUSS-SOLO-UNDERSTANDING': 'The Speaking Student',
  'STUDENT-DISCUSS-SOLO-GROWTH': 'The Verbal Scholar',
  'STUDENT-DISCUSS-GROUP-RELATIONSHIP': 'The Social Scholar',
  'STUDENT-DISCUSS-GROUP-DOUBTS': 'The Group Debater',
  'STUDENT-DISCUSS-GROUP-CRISIS': 'The Sharing Student',
  'STUDENT-DISCUSS-GROUP-MINISTRY': 'The Discussion Scholar',
  'STUDENT-DISCUSS-GROUP-UNDERSTANDING': 'The Conversational Student',
  'STUDENT-DISCUSS-GROUP-GROWTH': 'The Talking Community',
  'STUDENT-DISCUSS-FACILITATE-RELATIONSHIP': 'The Student Leader',
  'STUDENT-DISCUSS-FACILITATE-DOUBTS': 'The Scholar Guide',
  'STUDENT-DISCUSS-FACILITATE-CRISIS': 'The Academic Healer',
  'STUDENT-DISCUSS-FACILITATE-MINISTRY': 'The Teaching Student',
  'STUDENT-DISCUSS-FACILITATE-UNDERSTANDING': 'The Student Facilitator',
  'STUDENT-DISCUSS-FACILITATE-GROWTH': 'The Learning Leader',
  'STUDENT-DISCUSS-SEEKING-RELATIONSHIP': 'The Social Scholar',
  'STUDENT-DISCUSS-SEEKING-DOUBTS': 'The Community Scholar',
  'STUDENT-DISCUSS-SEEKING-CRISIS': 'The Connection Student',
  'STUDENT-DISCUSS-SEEKING-MINISTRY': 'The Relational Scholar',
  'STUDENT-DISCUSS-SEEKING-UNDERSTANDING': 'The Social Student',
  'STUDENT-DISCUSS-SEEKING-GROWTH': 'The Conversational Journey',
  'STUDENT-DISCUSS-MIXED-RELATIONSHIP': 'The Balanced Communicator',
  'STUDENT-DISCUSS-MIXED-DOUBTS': 'The Flexible Scholar',
  'STUDENT-DISCUSS-MIXED-CRISIS': 'The Adaptive Student',
  'STUDENT-DISCUSS-MIXED-MINISTRY': 'The Versatile Scholar',
  'STUDENT-DISCUSS-MIXED-UNDERSTANDING': 'The Holistic Student',
  'STUDENT-DISCUSS-MIXED-GROWTH': 'The Complete Communicator',

  // --- STUDENT + INTERACTIVE (30) ---
  'STUDENT-INTERACTIVE-SOLO-RELATIONSHIP': 'The Hands-On Scholar',
  'STUDENT-INTERACTIVE-SOLO-DOUBTS': 'The Active Student',
  'STUDENT-INTERACTIVE-SOLO-CRISIS': 'The Practical Learner',
  'STUDENT-INTERACTIVE-SOLO-MINISTRY': 'The Experiential Student',
  'STUDENT-INTERACTIVE-SOLO-UNDERSTANDING': 'The Kinesthetic Student',
  'STUDENT-INTERACTIVE-SOLO-GROWTH': 'The Action Scholar',
  'STUDENT-INTERACTIVE-GROUP-RELATIONSHIP': 'The Group Experiencer',
  'STUDENT-INTERACTIVE-GROUP-DOUBTS': 'The Active Inquirer',
  'STUDENT-INTERACTIVE-GROUP-CRISIS': 'The Hands-On Healer',
  'STUDENT-INTERACTIVE-GROUP-MINISTRY': 'The Practical Team Player',
  'STUDENT-INTERACTIVE-GROUP-UNDERSTANDING': 'The Interactive Learner',
  'STUDENT-INTERACTIVE-GROUP-GROWTH': 'The Active Community',
  'STUDENT-INTERACTIVE-FACILITATE-RELATIONSHIP': 'The Experiential Leader',
  'STUDENT-INTERACTIVE-FACILITATE-DOUBTS': 'The Active Guide',
  'STUDENT-INTERACTIVE-FACILITATE-CRISIS': 'The Practical Healer',
  'STUDENT-INTERACTIVE-FACILITATE-MINISTRY': 'The Hands-On Facilitator',
  'STUDENT-INTERACTIVE-FACILITATE-UNDERSTANDING': 'The Experiential Teacher',
  'STUDENT-INTERACTIVE-FACILITATE-GROWTH': 'The Action Leader',
  'STUDENT-INTERACTIVE-SEEKING-RELATIONSHIP': 'The Active Seeker',
  'STUDENT-INTERACTIVE-SEEKING-DOUBTS': 'The Hands-On Questioner',
  'STUDENT-INTERACTIVE-SEEKING-CRISIS': 'The Practical Searcher',
  'STUDENT-INTERACTIVE-SEEKING-MINISTRY': 'The Action Servant',
  'STUDENT-INTERACTIVE-SEEKING-UNDERSTANDING': 'The Experiential Seeker',
  'STUDENT-INTERACTIVE-SEEKING-GROWTH': 'The Interactive Journey',
  'STUDENT-INTERACTIVE-MIXED-RELATIONSHIP': 'The Versatile Doer',
  'STUDENT-INTERACTIVE-MIXED-DOUBTS': 'The Adaptive Experiencer',
  'STUDENT-INTERACTIVE-MIXED-CRISIS': 'The Flexible Student',
  'STUDENT-INTERACTIVE-MIXED-MINISTRY': 'The Multi-Modal Scholar',
  'STUDENT-INTERACTIVE-MIXED-UNDERSTANDING': 'The Dynamic Student',
  'STUDENT-INTERACTIVE-MIXED-GROWTH': 'The Holistic Actor',

  // --- STUDENT + PATTERNS (30) ---
  'STUDENT-PATTERNS-SOLO-RELATIONSHIP': 'The Detective Scholar',
  'STUDENT-PATTERNS-SOLO-DOUBTS': 'The Pattern Student',
  'STUDENT-PATTERNS-SOLO-CRISIS': 'The Meaning Learner',
  'STUDENT-PATTERNS-SOLO-MINISTRY': 'The Systematic Student',
  'STUDENT-PATTERNS-SOLO-UNDERSTANDING': 'The Discovery Student',
  'STUDENT-PATTERNS-SOLO-GROWTH': 'The Explorer Scholar',
  'STUDENT-PATTERNS-GROUP-RELATIONSHIP': 'The Group Detective',
  'STUDENT-PATTERNS-GROUP-DOUBTS': 'The Collective Student',
  'STUDENT-PATTERNS-GROUP-CRISIS': 'The Shared Explorer',
  'STUDENT-PATTERNS-GROUP-MINISTRY': 'The Team Detective',
  'STUDENT-PATTERNS-GROUP-UNDERSTANDING': 'The Pattern Learner',
  'STUDENT-PATTERNS-GROUP-GROWTH': 'The Discovery Community',
  'STUDENT-PATTERNS-FACILITATE-RELATIONSHIP': 'The Pattern Leader',
  'STUDENT-PATTERNS-FACILITATE-DOUBTS': 'The Detective Guide',
  'STUDENT-PATTERNS-FACILITATE-CRISIS': 'The Connection Healer',
  'STUDENT-PATTERNS-FACILITATE-MINISTRY': 'The Systematic Facilitator',
  'STUDENT-PATTERNS-FACILITATE-UNDERSTANDING': 'The Discovery Teacher',
  'STUDENT-PATTERNS-FACILITATE-GROWTH': 'The Pattern Shepherd',
  'STUDENT-PATTERNS-SEEKING-RELATIONSHIP': 'The Connection Scholar',
  'STUDENT-PATTERNS-SEEKING-DOUBTS': 'The Pattern Seeker',
  'STUDENT-PATTERNS-SEEKING-CRISIS': 'The Meaning Hunter',
  'STUDENT-PATTERNS-SEEKING-MINISTRY': 'The Detective Servant',
  'STUDENT-PATTERNS-SEEKING-UNDERSTANDING': 'The Discovery Seeker',
  'STUDENT-PATTERNS-SEEKING-GROWTH': 'The Pattern Journey',
  'STUDENT-PATTERNS-MIXED-RELATIONSHIP': 'The Flexible Detective',
  'STUDENT-PATTERNS-MIXED-DOUBTS': 'The Adaptive Student',
  'STUDENT-PATTERNS-MIXED-CRISIS': 'The Versatile Explorer',
  'STUDENT-PATTERNS-MIXED-MINISTRY': 'The Multi-Modal Detective',
  'STUDENT-PATTERNS-MIXED-UNDERSTANDING': 'The Holistic Scholar',
  'STUDENT-PATTERNS-MIXED-GROWTH': 'The Comprehensive Explorer',

  // --- EXPLORING + READ (30) ---
  'EXPLORING-READ-SOLO-RELATIONSHIP': 'The Solitary Explorer',
  'EXPLORING-READ-SOLO-DOUBTS': 'The Questioning Reader',
  'EXPLORING-READ-SOLO-CRISIS': 'The Searching Soul',
  'EXPLORING-READ-SOLO-MINISTRY': 'The Reluctant Servant',
  'EXPLORING-READ-SOLO-UNDERSTANDING': 'The Curious Student',
  'EXPLORING-READ-SOLO-GROWTH': 'The Growing Explorer',
  'EXPLORING-READ-GROUP-RELATIONSHIP': 'The Social Explorer',
  'EXPLORING-READ-GROUP-DOUBTS': 'The Group Questioner',
  'EXPLORING-READ-GROUP-CRISIS': 'The Supported Seeker',
  'EXPLORING-READ-GROUP-MINISTRY': 'The Hesitant Servant',
  'EXPLORING-READ-GROUP-UNDERSTANDING': 'The Community Learner',
  'EXPLORING-READ-GROUP-GROWTH': 'The Shared Journey',
  'EXPLORING-READ-FACILITATE-RELATIONSHIP': 'The Reluctant Leader',
  'EXPLORING-READ-FACILITATE-DOUBTS': 'The Questioning Guide',
  'EXPLORING-READ-FACILITATE-CRISIS': 'The Wounded Healer',
  'EXPLORING-READ-FACILITATE-MINISTRY': 'The Uncertain Facilitator',
  'EXPLORING-READ-FACILITATE-UNDERSTANDING': 'The Learning Leader',
  'EXPLORING-READ-FACILITATE-GROWTH': 'The Growing Guide',
  'EXPLORING-READ-SEEKING-RELATIONSHIP': 'The Lonely Seeker',
  'EXPLORING-READ-SEEKING-DOUBTS': 'The Isolated Questioner',
  'EXPLORING-READ-SEEKING-CRISIS': 'The Desperate Searcher',
  'EXPLORING-READ-SEEKING-MINISTRY': 'The Solitary Servant',
  'EXPLORING-READ-SEEKING-UNDERSTANDING': 'The Hungry Learner',
  'EXPLORING-READ-SEEKING-GROWTH': 'The Yearning Heart',
  'EXPLORING-READ-MIXED-RELATIONSHIP': 'The Balanced Explorer',
  'EXPLORING-READ-MIXED-DOUBTS': 'The Flexible Questioner',
  'EXPLORING-READ-MIXED-CRISIS': 'The Adaptive Seeker',
  'EXPLORING-READ-MIXED-MINISTRY': 'The Versatile Explorer',
  'EXPLORING-READ-MIXED-UNDERSTANDING': 'The Open Learner',
  'EXPLORING-READ-MIXED-GROWTH': 'The Holistic Seeker',

  // --- EXPLORING + VISUAL (30) ---
  'EXPLORING-VISUAL-SOLO-RELATIONSHIP': 'The Artistic Explorer',
  'EXPLORING-VISUAL-SOLO-DOUBTS': 'The Visual Questioner',
  'EXPLORING-VISUAL-SOLO-CRISIS': 'The Creative Searcher',
  'EXPLORING-VISUAL-SOLO-MINISTRY': 'The Inspired Explorer',
  'EXPLORING-VISUAL-SOLO-UNDERSTANDING': 'The Picture Seeker',
  'EXPLORING-VISUAL-SOLO-GROWTH': 'The Imaginative Journey',
  'EXPLORING-VISUAL-GROUP-RELATIONSHIP': 'The Shared Vision',
  'EXPLORING-VISUAL-GROUP-DOUBTS': 'The Group Artist',
  'EXPLORING-VISUAL-GROUP-CRISIS': 'The Supported Creator',
  'EXPLORING-VISUAL-GROUP-MINISTRY': 'The Visual Explorer',
  'EXPLORING-VISUAL-GROUP-UNDERSTANDING': 'The Collaborative Visualizer',
  'EXPLORING-VISUAL-GROUP-GROWTH': 'The Creative Community',
  'EXPLORING-VISUAL-FACILITATE-RELATIONSHIP': 'The Visual Leader',
  'EXPLORING-VISUAL-FACILITATE-DOUBTS': 'The Artistic Guide',
  'EXPLORING-VISUAL-FACILITATE-CRISIS': 'The Creative Healer',
  'EXPLORING-VISUAL-FACILITATE-MINISTRY': 'The Inspiring Facilitator',
  'EXPLORING-VISUAL-FACILITATE-UNDERSTANDING': 'The Teaching Artist',
  'EXPLORING-VISUAL-FACILITATE-GROWTH': 'The Visual Shepherd',
  'EXPLORING-VISUAL-SEEKING-RELATIONSHIP': 'The Artistic Wanderer',
  'EXPLORING-VISUAL-SEEKING-DOUBTS': 'The Visual Seeker',
  'EXPLORING-VISUAL-SEEKING-CRISIS': 'The Creative Refuge',
  'EXPLORING-VISUAL-SEEKING-MINISTRY': 'The Inspired Nomad',
  'EXPLORING-VISUAL-SEEKING-UNDERSTANDING': 'The Picture Hunter',
  'EXPLORING-VISUAL-SEEKING-GROWTH': 'The Colorful Journey',
  'EXPLORING-VISUAL-MIXED-RELATIONSHIP': 'The Flexible Artist',
  'EXPLORING-VISUAL-MIXED-DOUBTS': 'The Adaptive Visualizer',
  'EXPLORING-VISUAL-MIXED-CRISIS': 'The Creative Adapter',
  'EXPLORING-VISUAL-MIXED-MINISTRY': 'The Versatile Creator',
  'EXPLORING-VISUAL-MIXED-UNDERSTANDING': 'The Visual Explorer',
  'EXPLORING-VISUAL-MIXED-GROWTH': 'The Creative Synthesizer',

  // --- EXPLORING + DISCUSS (30) ---
  'EXPLORING-DISCUSS-SOLO-RELATIONSHIP': 'The Self Questioner',
  'EXPLORING-DISCUSS-SOLO-DOUBTS': 'The Internal Explorer',
  'EXPLORING-DISCUSS-SOLO-CRISIS': 'The Talking Processor',
  'EXPLORING-DISCUSS-SOLO-UNDERSTANDING': 'The Speaking Seeker',
  'EXPLORING-DISCUSS-SOLO-MINISTRY': 'The Vocal Explorer',
  'EXPLORING-DISCUSS-SOLO-GROWTH': 'The Verbal Explorer',
  'EXPLORING-DISCUSS-GROUP-RELATIONSHIP': 'The Social Questioner',
  'EXPLORING-DISCUSS-GROUP-DOUBTS': 'The Group Explorer',
  'EXPLORING-DISCUSS-GROUP-CRISIS': 'The Sharing Seeker',
  'EXPLORING-DISCUSS-GROUP-MINISTRY': 'The Conversational Explorer',
  'EXPLORING-DISCUSS-GROUP-UNDERSTANDING': 'The Discussion Seeker',
  'EXPLORING-DISCUSS-GROUP-GROWTH': 'The Growing Leader',
  'EXPLORING-DISCUSS-FACILITATE-RELATIONSHIP': 'The Natural Leader',
  'EXPLORING-DISCUSS-FACILITATE-DOUBTS': 'The Question Master',
  'EXPLORING-DISCUSS-FACILITATE-CRISIS': 'The Healing Facilitator',
  'EXPLORING-DISCUSS-FACILITATE-MINISTRY': 'The Born Guide',
  'EXPLORING-DISCUSS-FACILITATE-UNDERSTANDING': 'The Teaching Talker',
  'EXPLORING-DISCUSS-FACILITATE-GROWTH': 'The Growing Leader',
  'EXPLORING-DISCUSS-SEEKING-RELATIONSHIP': 'The Social Seeker',
  'EXPLORING-DISCUSS-SEEKING-DOUBTS': 'The Community Questioner',
  'EXPLORING-DISCUSS-SEEKING-CRISIS': 'The Connection Seeker',
  'EXPLORING-DISCUSS-SEEKING-MINISTRY': 'The People Explorer',
  'EXPLORING-DISCUSS-SEEKING-UNDERSTANDING': 'The Social Student',
  'EXPLORING-DISCUSS-SEEKING-GROWTH': 'The Relational Journey',
  'EXPLORING-DISCUSS-MIXED-RELATIONSHIP': 'The Balanced Talker',
  'EXPLORING-DISCUSS-MIXED-DOUBTS': 'The Flexible Explorer',
  'EXPLORING-DISCUSS-MIXED-CRISIS': 'The Adaptive Processor',
  'EXPLORING-DISCUSS-MIXED-MINISTRY': 'The Versatile Speaker',
  'EXPLORING-DISCUSS-MIXED-UNDERSTANDING': 'The Social Synthesizer',
  'EXPLORING-DISCUSS-MIXED-GROWTH': 'The Holistic Communicator',

  // --- EXPLORING + INTERACTIVE (30) ---
  'EXPLORING-INTERACTIVE-SOLO-RELATIONSHIP': 'The Hands-On Explorer',
  'EXPLORING-INTERACTIVE-SOLO-DOUBTS': 'The Active Questioner',
  'EXPLORING-INTERACTIVE-SOLO-CRISIS': 'The Doing Explorer',
  'EXPLORING-INTERACTIVE-SOLO-MINISTRY': 'The Practical Seeker',
  'EXPLORING-INTERACTIVE-SOLO-UNDERSTANDING': 'The Kinesthetic Explorer',
  'EXPLORING-INTERACTIVE-SOLO-GROWTH': 'The Action Journey',
  'EXPLORING-INTERACTIVE-GROUP-RELATIONSHIP': 'The Group Experiencer',
  'EXPLORING-INTERACTIVE-GROUP-DOUBTS': 'The Active Inquirer',
  'EXPLORING-INTERACTIVE-GROUP-CRISIS': 'The Hands-On Healer',
  'EXPLORING-INTERACTIVE-GROUP-MINISTRY': 'The Practical Explorer',
  'EXPLORING-INTERACTIVE-GROUP-UNDERSTANDING': 'The Interactive Learner',
  'EXPLORING-INTERACTIVE-GROUP-GROWTH': 'The Active Community',
  'EXPLORING-INTERACTIVE-FACILITATE-RELATIONSHIP': 'The Experiential Leader',
  'EXPLORING-INTERACTIVE-FACILITATE-DOUBTS': 'The Active Guide',
  'EXPLORING-INTERACTIVE-FACILITATE-CRISIS': 'The Practical Healer',
  'EXPLORING-INTERACTIVE-FACILITATE-MINISTRY': 'The Hands-On Facilitator',
  'EXPLORING-INTERACTIVE-FACILITATE-UNDERSTANDING': 'The Experiential Teacher',
  'EXPLORING-INTERACTIVE-FACILITATE-GROWTH': 'The Action Leader',
  'EXPLORING-INTERACTIVE-SEEKING-RELATIONSHIP': 'The Active Seeker',
  'EXPLORING-INTERACTIVE-SEEKING-DOUBTS': 'The Hands-On Questioner',
  'EXPLORING-INTERACTIVE-SEEKING-CRISIS': 'The Practical Searcher',
  'EXPLORING-INTERACTIVE-SEEKING-MINISTRY': 'The Action Explorer',
  'EXPLORING-INTERACTIVE-SEEKING-UNDERSTANDING': 'The Experiential Seeker',
  'EXPLORING-INTERACTIVE-SEEKING-GROWTH': 'The Interactive Quest',
  'EXPLORING-INTERACTIVE-MIXED-RELATIONSHIP': 'The Versatile Doer',
  'EXPLORING-INTERACTIVE-MIXED-DOUBTS': 'The Adaptive Experiencer',
  'EXPLORING-INTERACTIVE-MIXED-CRISIS': 'The Flexible Explorer',
  'EXPLORING-INTERACTIVE-MIXED-MINISTRY': 'The Multi-Modal Seeker',
  'EXPLORING-INTERACTIVE-MIXED-UNDERSTANDING': 'The Dynamic Explorer',
  'EXPLORING-INTERACTIVE-MIXED-GROWTH': 'The Holistic Actor',

  // --- EXPLORING + PATTERNS (30) ---
  'EXPLORING-PATTERNS-SOLO-RELATIONSHIP': 'The Pattern Seeker',
  'EXPLORING-PATTERNS-SOLO-DOUBTS': 'The Connection Questioner',
  'EXPLORING-PATTERNS-SOLO-CRISIS': 'The Meaning Explorer',
  'EXPLORING-PATTERNS-SOLO-MINISTRY': 'The Systematic Seeker',
  'EXPLORING-PATTERNS-SOLO-UNDERSTANDING': 'The Detective Explorer',
  'EXPLORING-PATTERNS-SOLO-GROWTH': 'The Discovery Journey',
  'EXPLORING-PATTERNS-GROUP-RELATIONSHIP': 'The Group Detective',
  'EXPLORING-PATTERNS-GROUP-DOUBTS': 'The Collective Investigator',
  'EXPLORING-PATTERNS-GROUP-CRISIS': 'The Shared Investigator',
  'EXPLORING-PATTERNS-GROUP-MINISTRY': 'The Team Detective',
  'EXPLORING-PATTERNS-GROUP-UNDERSTANDING': 'The Pattern Explorer',
  'EXPLORING-PATTERNS-GROUP-GROWTH': 'The Discovery Group',
  'EXPLORING-PATTERNS-FACILITATE-RELATIONSHIP': 'The Pattern Leader',
  'EXPLORING-PATTERNS-FACILITATE-DOUBTS': 'The Detective Guide',
  'EXPLORING-PATTERNS-FACILITATE-CRISIS': 'The Connection Healer',
  'EXPLORING-PATTERNS-FACILITATE-MINISTRY': 'The Systematic Facilitator',
  'EXPLORING-PATTERNS-FACILITATE-UNDERSTANDING': 'The Discovery Teacher',
  'EXPLORING-PATTERNS-FACILITATE-GROWTH': 'The Pattern Shepherd',
  'EXPLORING-PATTERNS-SEEKING-RELATIONSHIP': 'The Connection Hunter',
  'EXPLORING-PATTERNS-SEEKING-DOUBTS': 'The Pattern Questioner',
  'EXPLORING-PATTERNS-SEEKING-CRISIS': 'The Meaning Hunter',
  'EXPLORING-PATTERNS-SEEKING-MINISTRY': 'The Detective Explorer',
  'EXPLORING-PATTERNS-SEEKING-UNDERSTANDING': 'The Discovery Seeker',
  'EXPLORING-PATTERNS-SEEKING-GROWTH': 'The Pattern Journey',
  'EXPLORING-PATTERNS-MIXED-RELATIONSHIP': 'The Flexible Detective',
  'EXPLORING-PATTERNS-MIXED-DOUBTS': 'The Adaptive Explorer',
  'EXPLORING-PATTERNS-MIXED-CRISIS': 'The Versatile Seeker',
  'EXPLORING-PATTERNS-MIXED-MINISTRY': 'The Multi-Modal Detective',
  'EXPLORING-PATTERNS-MIXED-UNDERSTANDING': 'The Holistic Explorer',
  'EXPLORING-PATTERNS-MIXED-GROWTH': 'The Comprehensive Explorer',
};

// ============ Lookup Function ============

/**
 * Get the unique persona name from the full 750-persona map
 * based on all 4 quiz dimensions.
 */
export function getPersonaName(
  background: SpiritualBackground,
  learningStyle: LearningStyle,
  community: CommunityPreference,
  season: CurrentSeason,
): string {
  const key = `${BG_CODE[background]}-${LEARNING_CODE[learningStyle]}-${COMMUNITY_CODE[community]}-${SEASON_CODE[season]}`;
  return PERSONA_NAMES[key] ?? 'The Unique Seeker';
}

/**
 * Build the persona key string from quiz answers (e.g. "NEW-READ-SOLO-RELATIONSHIP").
 */
export function getPersonaKey(
  background: SpiritualBackground,
  learningStyle: LearningStyle,
  community: CommunityPreference,
  season: CurrentSeason,
): string {
  return `${BG_CODE[background]}-${LEARNING_CODE[learningStyle]}-${COMMUNITY_CODE[community]}-${SEASON_CODE[season]}`;
}
