// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzhbewjkabdjwetimchs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6aGJld2prYWJkandldGltY2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2NTU0NzQsImV4cCI6MjA4NDIzMTQ3NH0.E-B28X9frtMTGISdnKXg8R8RFVgv0SN66CNb9Hax1cA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});